version: '3.0'
services:
    # MongoDB service holding the URL data.
    mongodb:
        image: mongo:3.4
        ports:
            - 27017:27017
        volumes:
            - ./mongo-data:/data/db

    # Memcached.
    memcached:
        image: memcached:1.4.36
        ports:
            - 11211:11211

    # urlinfo API service.
    apiservice:
        build: .
        ports:
            - 8001:8001
        environment:
            - CONFIG_PORT=8001
            - CONFIG_DEBUG=true
        links:
            - mongodb
            - memcached

    # Seed MongoDB with initial data set downloaded from http://www.phishtank.com/
    # Seeding additionally takes the URL from the phishtank data and breaks it out into
    # multiple attributes while removing additional info that isn't needed for this example.
    mongo-seed:
        build: seed
        links:
            - mongodb

volumes:
    mongo-data: {}
